name: movie
description: 'The Movie DB demo app written in Flutter.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Network & API
  http: ^1.1.0
  dio: ^5.3.2

  # UI & Animation
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Utils
  equatable: ^2.0.5
  intl: ^0.18.1
  json_annotation: ^4.8.1

  # Icons
  cupertino_icons: ^1.0.2

  halo:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
